name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: construir
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18,20,22]
    steps:
      - name: checkout codigo
        uses: actions/checkout@v4

      - name: Configurar nodejs
        uses: actions/setup-node@v4
        with:
          node-verson: ${{matrix.node-version}}
          cache: 'yarn'
      - name: install dependencies
        run: yarn

      - name: run test
        run: yarn test

